export interface Problem {
  id: string;
  title: string;
  difficulty: 'easy' | 'medium' | 'hard';
  category: string;
  description: string;
  examples: Array<{
    input: string;
    output: string;
    explanation?: string;
  }>;
  starterCode: string;
  solution: string;
  testCases: Array<{
    input: unknown;
    expectedOutput: unknown;
    description?: string;
  }>;
  hints: string[];
}

export const problem: Problem = {
    id: 'array-from',
    title: 'Array.from with Mapping',
    difficulty: 'medium',
    category: 'Array Methods',
    description: `## In-Depth Explanation

\`Array.from()\` is a versatile method that creates a new array from an iterable or array-like object. When combined with a mapping function as the second argument, it becomes a powerful tool for generating sequences and transforming data.

The syntax \`Array.from({ length: n }, mapFn)\` creates an array of length \`n\`, where each element is generated by calling \`mapFn\` with the index. This is more elegant than using loops or \`Array(n).fill().map()\` because it handles the mapping in a single operation.

The key advantage is that \`Array.from()\` works with any iterable (strings, Sets, Maps, NodeLists, etc.) and can transform them into arrays while applying a mapping function, all in one step.

## Importance

\`Array.from()\` is essential for array creation because:

- **Sequence Generation**: Creates number sequences, ranges, and patterns easily
- **Iterable Conversion**: Converts any iterable to an array
- **Mapping Integration**: Combines creation and transformation in one step
- **Performance**: More efficient than manual loops for array creation
- **Readability**: Clear intent - "create array from this pattern"
- **Flexibility**: Works with array-like objects (NodeLists, arguments, etc.)

## Usefulness & Practical Applications

This method is used extensively in modern JavaScript:

- **Sequence Generation**: Creating number sequences, date ranges, or custom patterns
- **DOM Manipulation**: Converting NodeLists to arrays for array methods
- **String Processing**: Converting strings to character arrays with transformations
- **Test Data**: Generating test data arrays with specific patterns
- **Pagination**: Creating page number arrays for pagination UI
- **Grid Generation**: Creating 2D arrays for game boards or grids
- **Mock Data**: Generating mock data for development and testing
- **Algorithm Implementation**: Creating arrays for algorithms that need indexed sequences

**Challenge:** Create arrays from various sources using Array.from.`,
    examples: [
      {
        input: `Array.from({ length: 5 }, (_, i) => i * 2)`,
        output: `[0, 2, 4, 6, 8]`,
        explanation: 'Create array of even numbers',
      },
    ],
    starterCode: `function createNumberSequence(length, start = 0, step = 1) {
  // TODO: Use Array.from to create sequence
  // Array.from({ length: n }, (_, i) => ...)
  return [];
}

function createAlphabet() {
  // TODO: Use Array.from to create ['a', 'b', 'c', ..., 'z']
  // Hint: String.fromCharCode(97) is 'a', 98 is 'b', etc.
  return [];
}

console.log('Sequence:', createNumberSequence(5, 0, 2));
console.log('Alphabet:', createAlphabet());`,
    solution: `function createNumberSequence(length, start = 0, step = 1) {
  return Array.from({ length }, (_, i) => start + i * step);
}

function createAlphabet() {
  return Array.from({ length: 26 }, (_, i) => String.fromCharCode(97 + i));
}`,
    testCases: [
      {
        input: [5, 0, 2],
        expectedOutput: [0, 2, 4, 6, 8],
        description: 'createNumberSequence',
      },
      {
        input: [],
        expectedOutput: [
          'a',
          'b',
          'c',
          'd',
          'e',
          'f',
          'g',
          'h',
          'i',
          'j',
          'k',
          'l',
          'm',
          'n',
          'o',
          'p',
          'q',
          'r',
          's',
          't',
          'u',
          'v',
          'w',
          'x',
          'y',
          'z',
        ],
        description: 'createAlphabet',
      },
    ],
    hints: [
      'Array.from({ length: n }, mapFn) creates array with n elements',
      'Second parameter is mapping function: (_, index) => value',
      'Useful for creating sequences, ranges, or transforming iterables',
    ],
  };
