export interface Problem {
  id: string;
  title: string;
  difficulty: 'easy' | 'medium' | 'hard';
  category: string;
  description: string;
  examples: Array<{
    input: string;
    output: string;
    explanation?: string;
  }>;
  starterCode: string;
  solution: string;
  testCases: Array<{
    input: unknown;
    expectedOutput: unknown;
    description?: string;
  }>;
  hints: string[];
}

export const problem: Problem = {
  id: 'array-from',
  title: 'Array.from with Mapping',
  difficulty: 'medium',
  category: 'Array Methods',
  description: `<h2>In-Depth Explanation</h2>

<p><code>Array.from()</code> is a versatile method that creates a new array from an iterable or array-like object. When combined with a mapping function as the second argument, it becomes a powerful tool for generating sequences and transforming data.</p>

<p>The syntax <code>Array.from({ length: n }, mapFn)</code> creates an array of length <code>n</code>, where each element is generated by calling <code>mapFn</code> with the index. This is more elegant than using loops or <code>Array(n).fill().map()</code> because it handles the mapping in a single operation.</p>

<p>The key advantage is that <code>Array.from()</code> works with any iterable (strings, Sets, Maps, NodeLists, etc.) and can transform them into arrays while applying a mapping function, all in one step.</p>

<h2>Importance</h2>

<p><code>Array.from()</code> is essential for array creation because:</p>

<ul>
  <li><strong>Sequence Generation</strong>: Creates number sequences, ranges, and patterns easily</li>
  <li><strong>Iterable Conversion</strong>: Converts any iterable to an array</li>
  <li><strong>Mapping Integration</strong>: Combines creation and transformation in one step</li>
  <li><strong>Performance</strong>: More efficient than manual loops for array creation</li>
  <li><strong>Readability</strong>: Clear intent - "create array from this pattern"</li>
  <li><strong>Flexibility</strong>: Works with array-like objects (NodeLists, arguments, etc.)</li>
</ul>

<h2>Usefulness & Practical Applications</h2>

<p>This method is used extensively in modern JavaScript:</p>

<ul>
  <li><strong>Sequence Generation</strong>: Creating number sequences, date ranges, or custom patterns</li>
  <li><strong>DOM Manipulation</strong>: Converting NodeLists to arrays for array methods</li>
  <li><strong>String Processing</strong>: Converting strings to character arrays with transformations</li>
  <li><strong>Test Data</strong>: Generating test data arrays with specific patterns</li>
  <li><strong>Pagination</strong>: Creating page number arrays for pagination UI</li>
  <li><strong>Grid Generation</strong>: Creating 2D arrays for game boards or grids</li>
  <li><strong>Mock Data</strong>: Generating mock data for development and testing</li>
  <li><strong>Algorithm Implementation</strong>: Creating arrays for algorithms that need indexed sequences</li>
</ul>

<p><strong>Challenge:</strong> Create arrays from various sources using Array.from.</p>`,
  examples: [
    {
      input: `Array.from({ length: 5 }, (_, i) => i * 2)`,
      output: `[0, 2, 4, 6, 8]`,
      explanation: 'Create array of even numbers',
    },
  ],
  starterCode: `function createNumberSequence(length, start = 0, step = 1) {
  // TODO: Use Array.from to create sequence
  // Array.from({ length: n }, (_, i) => ...)
  return [];
}

function createAlphabet() {
  // TODO: Use Array.from to create ['a', 'b', 'c', ..., 'z']
  // Hint: String.fromCharCode(97) is 'a', 98 is 'b', etc.
  return [];
}

console.log('Sequence:', createNumberSequence(5, 0, 2));
console.log('Alphabet:', createAlphabet());`,
  solution: `function createNumberSequence(length, start = 0, step = 1) {
  return Array.from({ length }, (_, i) => start + i * step);
}

function createAlphabet() {
  return Array.from({ length: 26 }, (_, i) => String.fromCharCode(97 + i));
}`,
  testCases: [
    {
      input: [5, 0, 2],
      expectedOutput: [0, 2, 4, 6, 8],
      description: 'createNumberSequence',
    },
    {
      input: [],
      expectedOutput: [
        'a',
        'b',
        'c',
        'd',
        'e',
        'f',
        'g',
        'h',
        'i',
        'j',
        'k',
        'l',
        'm',
        'n',
        'o',
        'p',
        'q',
        'r',
        's',
        't',
        'u',
        'v',
        'w',
        'x',
        'y',
        'z',
      ],
      description: 'createAlphabet',
    },
  ],
  hints: [
    'Array.from({ length: n }, mapFn) creates array with n elements',
    'Second parameter is mapping function: (_, index) => value',
    'Useful for creating sequences, ranges, or transforming iterables',
  ],
};
