export interface Problem {
  id: string;
  title: string;
  difficulty: 'easy' | 'medium' | 'hard';
  category: string;
  description: string;
  examples: Array<{
    input: string;
    output: string;
    explanation?: string;
  }>;
  starterCode: string;
  solution: string;
  testCases: Array<{
    input: unknown;
    expectedOutput: unknown;
    description?: string;
  }>;
  hints: string[];
}

export const problem: Problem = {
  id: 'array-from-tricks',
  title: 'Array.from Magic',
  difficulty: 'easy',
  category: 'Array Methods',
  description: `<h2>In-Depth Explanation</h2>

<p><code>Array.from()</code> is a versatile method for creating arrays from iterables or array-like objects. When combined with a mapping function, it becomes a powerful tool for generating sequences and transforming data.</p>

<p>The syntax <code>Array.from({ length: n }, mapFn)</code> creates an array of length <code>n</code>, where each element is generated by calling <code>mapFn</code> with the index. This is more elegant than loops or <code>Array(n).fill().map()</code> because it handles the mapping in a single operation.</p>

<p>Key tricks:</p>
<ul>
  <li><strong>Sequences</strong>: Generate number sequences, ranges, patterns</li>
  <li><strong>2D Arrays</strong>: Create grids/matrices by nesting Array.from calls</li>
  <li><strong>Iterable Conversion</strong>: Convert NodeLists, strings, Sets, Maps to arrays</li>
  <li><strong>Transformation</strong>: Combine creation and transformation in one step</li>
</ul>

<h2>Importance</h2>

<p>Array.from tricks are essential for array generation because:</p>

<ul>
  <li><strong>Sequence Generation</strong>: Create number sequences, date ranges, patterns easily</li>
  <li><strong>Grid Creation</strong>: Create 2D arrays for game boards, matrices, grids</li>
  <li><strong>Iterable Conversion</strong>: Convert any iterable to an array for array methods</li>
  <li><strong>Performance</strong>: More efficient than manual loops for array creation</li>
  <li><strong>Readability</strong>: Clear intent - "create array from this pattern"</li>
  <li><strong>Flexibility</strong>: Works with array-like objects (NodeLists, arguments, etc.)</li>
</ul>

<h2>Usefulness & Practical Applications</h2>

<p>These tricks are used extensively:</p>

<ul>
  <li><strong>Sequence Generation</strong>: Creating number sequences, date ranges, or custom patterns</li>
  <li><strong>Grid Generation</strong>: Creating 2D arrays for game boards or grids</li>
  <li><strong>DOM Manipulation</strong>: Converting NodeLists to arrays for array methods</li>
  <li><strong>String Processing</strong>: Converting strings to character arrays with transformations</li>
  <li><strong>Test Data</strong>: Generating test data arrays with specific patterns</li>
  <li><strong>Pagination</strong>: Creating page number arrays for pagination UI</li>
  <li><strong>Mock Data</strong>: Generating mock data for development and testing</li>
  <li><strong>Algorithm Implementation</strong>: Creating arrays for algorithms that need indexed sequences</li>
</ul>

<p><strong>Challenge:</strong> Generate sequences, convert NodeLists, and create 2D arrays.</p>`,
  examples: [
    {
      input: `Array.from({ length: 5 }, (_, i) => i)`,
      output: `[0, 1, 2, 3, 4]`,
      explanation: 'Generate sequence of numbers',
    },
  ],
  starterCode: `function range(start, end) {
  // TODO: Generate array from start to end (inclusive)
  // range(1, 5) → [1, 2, 3, 4, 5]

  return [];
}

function createGrid(rows, cols, defaultValue) {
  // TODO: Create 2D array filled with defaultValue
  // createGrid(2, 3, 0) → [[0, 0, 0], [0, 0, 0]]

  return [];
}

function toArray(arrayLike) {
  // TODO: Convert array-like object to real array
  // Works with NodeList, arguments, strings, etc.

  return [];
}

// Test
console.log(range(1, 5));
console.log(createGrid(2, 3, 0));
console.log(toArray('hello'));`,
  solution: `function range(start, end) {
  // Generate array from start to end (inclusive)
  // range(1, 5) → [1, 2, 3, 4, 5]
  const length = end - start + 1;
  return Array.from({ length }, (_, i) => start + i);
}

function createGrid(rows, cols, defaultValue) {
  // Create 2D array filled with defaultValue
  // createGrid(2, 3, 0) → [[0, 0, 0], [0, 0, 0]]
  return Array.from({ length: rows }, () =>
    Array.from({ length: cols }, () => defaultValue)
  );
}

function toArray(arrayLike) {
  // Convert array-like object to real array
  // Works with NodeList, arguments, strings, etc.
  return Array.from(arrayLike);
}`,
  testCases: [
    {
      input: [1, 5],
      expectedOutput: [1, 2, 3, 4, 5],
      description: 'range creates array from 1 to 5 inclusive',
    },
    {
      input: [0, 3],
      expectedOutput: [0, 1, 2, 3],
      description: 'range creates array from 0 to 3 inclusive',
    },
    {
      input: [-2, 2],
      expectedOutput: [-2, -1, 0, 1, 2],
      description: 'range handles negative start values',
    },
    {
      input: [2, 3, 0],
      expectedOutput: [
        [0, 0, 0],
        [0, 0, 0],
      ],
      description: 'createGrid creates 2x3 grid filled with 0',
    },
    {
      input: [3, 2, 'x'],
      expectedOutput: [
        ['x', 'x'],
        ['x', 'x'],
        ['x', 'x'],
      ],
      description: 'createGrid creates 3x2 grid filled with x',
    },
    {
      input: ['hello'],
      expectedOutput: ['h', 'e', 'l', 'l', 'o'],
      description: 'toArray converts string to character array',
    },
    {
      input: ['abc'],
      expectedOutput: ['a', 'b', 'c'],
      description: 'toArray converts string abc to array',
    },
  ],
  hints: [
    'Array.from({ length: n }) creates array of n undefined elements',
    'Second argument (_, index) => value maps each element',
    'For 2D arrays, nest Array.from calls',
  ],
};
