export interface Problem {
  id: string;
  title: string;
  difficulty: 'easy' | 'medium' | 'hard';
  category: string;
  description: string;
  examples: Array<{
    input: string;
    output: string;
    explanation?: string;
  }>;
  starterCode: string;
  solution: string;
  testCases: Array<{
    input: unknown;
    expectedOutput: unknown;
    description?: string;
  }>;
  hints: string[];
}

export const problem: Problem = {
  id: 'array-from-tricks',
  title: 'Array.from Magic',
  difficulty: 'easy',
  category: 'Array Methods',
  description: `## In-Depth Explanation

\`Array.from()\` is a versatile method for creating arrays from iterables or array-like objects. When combined with a mapping function, it becomes a powerful tool for generating sequences and transforming data.

The syntax \`Array.from({ length: n }, mapFn)\` creates an array of length \`n\`, where each element is generated by calling \`mapFn\` with the index. This is more elegant than loops or \`Array(n).fill().map()\` because it handles the mapping in a single operation.

Key tricks:
- **Sequences**: Generate number sequences, ranges, patterns
- **2D Arrays**: Create grids/matrices by nesting Array.from calls
- **Iterable Conversion**: Convert NodeLists, strings, Sets, Maps to arrays
- **Transformation**: Combine creation and transformation in one step

## Importance

Array.from tricks are essential for array generation because:

- **Sequence Generation**: Create number sequences, date ranges, patterns easily
- **Grid Creation**: Create 2D arrays for game boards, matrices, grids
- **Iterable Conversion**: Convert any iterable to an array for array methods
- **Performance**: More efficient than manual loops for array creation
- **Readability**: Clear intent - "create array from this pattern"
- **Flexibility**: Works with array-like objects (NodeLists, arguments, etc.)

## Usefulness & Practical Applications

These tricks are used extensively:

- **Sequence Generation**: Creating number sequences, date ranges, or custom patterns
- **Grid Generation**: Creating 2D arrays for game boards or grids
- **DOM Manipulation**: Converting NodeLists to arrays for array methods
- **String Processing**: Converting strings to character arrays with transformations
- **Test Data**: Generating test data arrays with specific patterns
- **Pagination**: Creating page number arrays for pagination UI
- **Mock Data**: Generating mock data for development and testing
- **Algorithm Implementation**: Creating arrays for algorithms that need indexed sequences

**Challenge:** Generate sequences, convert NodeLists, and create 2D arrays.`,
  examples: [
    {
      input: `Array.from({ length: 5 }, (_, i) => i)`,
      output: `[0, 1, 2, 3, 4]`,
      explanation: 'Generate sequence of numbers',
    },
  ],
  starterCode: `function range(start, end) {
  // TODO: Generate array from start to end (inclusive)
  // range(1, 5) → [1, 2, 3, 4, 5]

  return [];
}

function createGrid(rows, cols, defaultValue) {
  // TODO: Create 2D array filled with defaultValue
  // createGrid(2, 3, 0) → [[0, 0, 0], [0, 0, 0]]

  return [];
}

function toArray(arrayLike) {
  // TODO: Convert array-like object to real array
  // Works with NodeList, arguments, strings, etc.

  return [];
}

// Test
console.log(range(1, 5));
console.log(createGrid(2, 3, 0));
console.log(toArray('hello'));`,
  solution: `function range(start, end) {
  return Array.from({ length: end - start + 1 }, (_, i) => start + i);
}

function createGrid(rows, cols, defaultValue) {
  return Array.from({ length: rows }, () =>
    Array.from({ length: cols }, () => defaultValue)
  );
}

function toArray(arrayLike) {
  return Array.from(arrayLike);
}`,
  testCases: [
    {
      input: [1, 5],
      expectedOutput: [1, 2, 3, 4, 5],
      description: 'range',
    },
    {
      input: [2, 3, 0],
      expectedOutput: [
        [0, 0, 0],
        [0, 0, 0],
      ],
      description: 'createGrid',
    },
    {
      input: ['hello'],
      expectedOutput: ['h', 'e', 'l', 'l', 'o'],
      description: 'toArray string',
    },
  ],
  hints: [
    'Array.from({ length: n }) creates array of n undefined elements',
    'Second argument (_, index) => value maps each element',
    'For 2D arrays, nest Array.from calls',
  ],
};
